# Generated by Django 5.0.6 on 2024-08-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Land Owner'), ('seeker', 'Land Seeker')], max_length=10),
        ),
    ]
