# Generated by Django 5.0.6 on 2025-04-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_faq_testimonial_landlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
