# Generated by Django 5.0.6 on 2025-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_land_description_land_image_land_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('facilitated', 'Facilitated')], default='pending', max_length=20),
        ),
    ]
