# Generated by Django 5.0.6 on 2024-08-25 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_landseeker_crop_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='landowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.landowner'),
        ),
    ]
