# Generated by Django 5.0.6 on 2024-08-31 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0012_alter_land_landowner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['sent_at'], 'verbose_name': 'Communication', 'verbose_name_plural': 'Communications'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['question'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['expressed_interest_date'], 'verbose_name': 'Interest', 'verbose_name_plural': 'Interests'},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['location', 'size'], 'verbose_name': 'Land', 'verbose_name_plural': 'Lands'},
        ),
        migrations.AlterModelOptions(
            name='landowner',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Landowner', 'verbose_name_plural': 'Landowners'},
        ),
        migrations.AlterModelOptions(
            name='landseeker',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Land Seeker', 'verbose_name_plural': 'Land Seekers'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['review_date'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='communication',
            name='landowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='myapp.landowner'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='myapp.landowner'),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='landowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.landowner'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['email'], name='myapp_myuse_email_138a11_idx'),
        ),
    ]
