# Generated by Django 5.0.6 on 2024-11-02 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_communication_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landowner',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Landowner', 'verbose_name_plural': 'Landowners'},
        ),
        migrations.AlterModelOptions(
            name='landseeker',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Land Seeker', 'verbose_name_plural': 'Land Seekers'},
        ),
        migrations.RemoveField(
            model_name='landowner',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='landseeker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='landowner',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='landseeker',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landseeker',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='landseeker',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='landseeker',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('water_availability', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='land_images/')),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
