# Generated by Django 5.0.6 on 2024-11-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_landowner_options_alter_landseeker_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={},
        ),
        migrations.AlterModelOptions(
            name='landowner',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Landowner', 'verbose_name_plural': 'Landowners'},
        ),
        migrations.AlterModelOptions(
            name='landseeker',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Land Seeker', 'verbose_name_plural': 'Land Seekers'},
        ),
        migrations.RemoveField(
            model_name='land',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='land',
            name='landowner',
        ),
        migrations.RemoveField(
            model_name='land',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='land',
            name='water_availability',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='land_name',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='size',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='water_availability',
        ),
        migrations.AddField(
            model_name='landlisting',
            name='land',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.land'),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='landseeker',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
