# Generated by Django 4.2.1 on 2024-11-12 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_land_options_alter_landowner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlisting',
            name='land',
        ),
        migrations.RemoveField(
            model_name='landlisting',
            name='price_per_month',
        ),
        migrations.AddField(
            model_name='landlisting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='land_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land_listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='size',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Size in acres or square meters', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='soil_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlisting',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='water_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
