# Generated by Django 4.2.1 on 2024-11-12 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_landlisting_land_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlisting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in acres or square meters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='water_availability',
            field=models.CharField(max_length=100),
        ),
    ]
